runtime: python
env: flex
entrypoint: gunicorn -b :$PORT transferableunitsbe:app

runtime_config:
  python_version: 2

threadsafe: true

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10